services:
  api:
    build: .
    container_name: pettech_api
    ports:
      - "3010:3010"
    env_file: .env
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    image: mongo:6
    container_name: mongodb_dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-devuser}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-devpass}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-nestdb}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # opcional: interface web para visualizar e testar o Mongo
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo_express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-devuser}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-devpass}
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH: "false"
    restart: unless-stopped

volumes:
  mongo_data:

